# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# Portions Copyright (C) Philipp Kewisch, 2019
---
name: Checkin
on: [push, pull_request]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "npm install eslint"
        run: npm install eslint

      - name: "ESLint"
        uses: "./"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
